# Ubuntu base image
FROM ubuntu:20.04

# build参数
ARG user=mi

ARG DEBIAN_FRONTEND=noninteractive

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list

RUN apt-get update
RUN apt install sudo -y
RUN apt install vim cmake catkin gdb-multiarch gcc g++ -y
RUN apt install locate lsb-release pkg-config pkg-config autoconf automake libtool -y
RUN apt install libpoco-dev libncurses-dev libasio-dev uuid-dev -y

# 添加用户：赋予sudo权限，指定密码
RUN useradd --create-home --no-log-init --shell /bin/bash ${user} \
    && adduser ${user} sudo \
    && echo "${user}:${user}" | chpasswd
RUN echo "${user} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

# 改变用户的UID和GID
RUN usermod -u 1000 ${user} && usermod -G 1000 ${user}
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV DISPLAY :1
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

USER ${user}
# 指定容器起来的工作目录
WORKDIR /home/${user}

CMD ["/bin/bash"]

# docker build -f ./DockerFile -t cyber_rt_build:0.1 .