#!/usr/bin/bash
_SETUP_PATH=$(cd `dirname $BASH_SOURCE[0]`; pwd)
PATH=$_SETUP_PATH/env/bin:$PATH
LD_LIBRARY_PATH=$_SETUP_PATH/env/lib:$LD_LIBRARY_PATH
LIBRARY_PATH=$_SETUP_PATH/env/lib:$LIBRARY_PATH

# 设置了CMAKE_PREFIX_PATH这个，编译过程中find_package 就能够找对位置
CMAKE_PREFIX_PATH=$_SETUP_PATH:$CMAKE_PREFIX_PATH

#  设置了PKG_CONFIG_PATH这个，编译过程中 pkg_check_modules 就能够找对位置
PKG_CONFIG_PATH=$_SETUP_PATH/env/lib/pkgconfig:$_SETUP_PATH/env/share:$PKG_CONFIG_PATH
export PATH LD_LIBRARY_PATH CMAKE_PREFIX_PATH PKG_CONFIG_PATH


#_SETUP_PATH=$(cd `dirname $BASH_SOURCE[0]`; pwd)
#PATH=$_SETUP_PATH/bin:$PATH
#PYTHONPATH=$_SETUP_PATH/lib/python3.6/site-packages:$PYTHONPATH
#LD_LIBRARY_PATH=$_SETUP_PATH/lib:$LD_LIBRARY_PATH
#LIBRARY_PATH=$_SETUP_PATH/lib:$LIBRARY_PATH
#CMAKE_PREFIX_PATH=$_SETUP_PATH:$CMAKE_PREFIX_PATH
#PKG_CONFIG_PATH=$_SETUP_PATH/lib/pkgconfig:$_SETUP_PATH/share/pkgconfig:$PKG_CONFIG_PATH
#export PATH LD_LIBRARY_PATH CMAKE_PREFIX_PATH PKG_CONFIG_PATH PYTHONPATH
