// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: class02.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_class02_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_class02_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_class02_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_class02_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_class02_2eproto;
namespace apollo {
namespace cyber {
namespace examples {
namespace proto {
class SimpleLocalization;
class SimpleLocalizationDefaultTypeInternal;
extern SimpleLocalizationDefaultTypeInternal _SimpleLocalization_default_instance_;
class SimplePlanning;
class SimplePlanningDefaultTypeInternal;
extern SimplePlanningDefaultTypeInternal _SimplePlanning_default_instance_;
}  // namespace proto
}  // namespace examples
}  // namespace cyber
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::cyber::examples::proto::SimpleLocalization* Arena::CreateMaybeMessage<::apollo::cyber::examples::proto::SimpleLocalization>(Arena*);
template<> ::apollo::cyber::examples::proto::SimplePlanning* Arena::CreateMaybeMessage<::apollo::cyber::examples::proto::SimplePlanning>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace cyber {
namespace examples {
namespace proto {

// ===================================================================

class SimplePlanning PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.examples.proto.SimplePlanning) */ {
 public:
  inline SimplePlanning() : SimplePlanning(nullptr) {}
  virtual ~SimplePlanning();

  SimplePlanning(const SimplePlanning& from);
  SimplePlanning(SimplePlanning&& from) noexcept
    : SimplePlanning() {
    *this = ::std::move(from);
  }

  inline SimplePlanning& operator=(const SimplePlanning& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimplePlanning& operator=(SimplePlanning&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SimplePlanning& default_instance();

  static inline const SimplePlanning* internal_default_instance() {
    return reinterpret_cast<const SimplePlanning*>(
               &_SimplePlanning_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SimplePlanning& a, SimplePlanning& b) {
    a.Swap(&b);
  }
  inline void Swap(SimplePlanning* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimplePlanning* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SimplePlanning* New() const final {
    return CreateMaybeMessage<SimplePlanning>(nullptr);
  }

  SimplePlanning* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SimplePlanning>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SimplePlanning& from);
  void MergeFrom(const SimplePlanning& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimplePlanning* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.examples.proto.SimplePlanning";
  }
  protected:
  explicit SimplePlanning(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_class02_2eproto);
    return ::descriptor_table_class02_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 1,
    kSeqFieldNumber = 2,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kHeadingFieldNumber = 5,
    kSpeedFieldNumber = 6,
  };
  // optional uint64 timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 seq = 2;
  bool has_seq() const;
  private:
  bool _internal_has_seq() const;
  public:
  void clear_seq();
  ::PROTOBUF_NAMESPACE_ID::uint64 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_seq() const;
  void _internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional double x = 3;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // optional double y = 4;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // optional double heading = 5;
  bool has_heading() const;
  private:
  bool _internal_has_heading() const;
  public:
  void clear_heading();
  double heading() const;
  void set_heading(double value);
  private:
  double _internal_heading() const;
  void _internal_set_heading(double value);
  public:

  // optional double speed = 6;
  bool has_speed() const;
  private:
  bool _internal_has_speed() const;
  public:
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.examples.proto.SimplePlanning)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 seq_;
  double x_;
  double y_;
  double heading_;
  double speed_;
  friend struct ::TableStruct_class02_2eproto;
};
// -------------------------------------------------------------------

class SimpleLocalization PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.examples.proto.SimpleLocalization) */ {
 public:
  inline SimpleLocalization() : SimpleLocalization(nullptr) {}
  virtual ~SimpleLocalization();

  SimpleLocalization(const SimpleLocalization& from);
  SimpleLocalization(SimpleLocalization&& from) noexcept
    : SimpleLocalization() {
    *this = ::std::move(from);
  }

  inline SimpleLocalization& operator=(const SimpleLocalization& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimpleLocalization& operator=(SimpleLocalization&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SimpleLocalization& default_instance();

  static inline const SimpleLocalization* internal_default_instance() {
    return reinterpret_cast<const SimpleLocalization*>(
               &_SimpleLocalization_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SimpleLocalization& a, SimpleLocalization& b) {
    a.Swap(&b);
  }
  inline void Swap(SimpleLocalization* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimpleLocalization* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SimpleLocalization* New() const final {
    return CreateMaybeMessage<SimpleLocalization>(nullptr);
  }

  SimpleLocalization* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SimpleLocalization>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SimpleLocalization& from);
  void MergeFrom(const SimpleLocalization& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimpleLocalization* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.examples.proto.SimpleLocalization";
  }
  protected:
  explicit SimpleLocalization(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_class02_2eproto);
    return ::descriptor_table_class02_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 1,
    kSeqFieldNumber = 2,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kZFieldNumber = 5,
    kHeadingFieldNumber = 6,
  };
  // optional uint64 timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 seq = 2;
  bool has_seq() const;
  private:
  bool _internal_has_seq() const;
  public:
  void clear_seq();
  ::PROTOBUF_NAMESPACE_ID::uint64 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_seq() const;
  void _internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional double x = 3;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // optional double y = 4;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // optional double z = 5;
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // optional double heading = 6;
  bool has_heading() const;
  private:
  bool _internal_has_heading() const;
  public:
  void clear_heading();
  double heading() const;
  void set_heading(double value);
  private:
  double _internal_heading() const;
  void _internal_set_heading(double value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.examples.proto.SimpleLocalization)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 seq_;
  double x_;
  double y_;
  double z_;
  double heading_;
  friend struct ::TableStruct_class02_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SimplePlanning

// optional uint64 timestamp = 1;
inline bool SimplePlanning::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SimplePlanning::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void SimplePlanning::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimplePlanning::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimplePlanning::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimplePlanning.timestamp)
  return _internal_timestamp();
}
inline void SimplePlanning::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  timestamp_ = value;
}
inline void SimplePlanning::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimplePlanning.timestamp)
}

// optional uint64 seq = 2;
inline bool SimplePlanning::_internal_has_seq() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SimplePlanning::has_seq() const {
  return _internal_has_seq();
}
inline void SimplePlanning::clear_seq() {
  seq_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimplePlanning::_internal_seq() const {
  return seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimplePlanning::seq() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimplePlanning.seq)
  return _internal_seq();
}
inline void SimplePlanning::_internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  seq_ = value;
}
inline void SimplePlanning::set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimplePlanning.seq)
}

// optional double x = 3;
inline bool SimplePlanning::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SimplePlanning::has_x() const {
  return _internal_has_x();
}
inline void SimplePlanning::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double SimplePlanning::_internal_x() const {
  return x_;
}
inline double SimplePlanning::x() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimplePlanning.x)
  return _internal_x();
}
inline void SimplePlanning::_internal_set_x(double value) {
  _has_bits_[0] |= 0x00000004u;
  x_ = value;
}
inline void SimplePlanning::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimplePlanning.x)
}

// optional double y = 4;
inline bool SimplePlanning::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool SimplePlanning::has_y() const {
  return _internal_has_y();
}
inline void SimplePlanning::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double SimplePlanning::_internal_y() const {
  return y_;
}
inline double SimplePlanning::y() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimplePlanning.y)
  return _internal_y();
}
inline void SimplePlanning::_internal_set_y(double value) {
  _has_bits_[0] |= 0x00000008u;
  y_ = value;
}
inline void SimplePlanning::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimplePlanning.y)
}

// optional double heading = 5;
inline bool SimplePlanning::_internal_has_heading() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool SimplePlanning::has_heading() const {
  return _internal_has_heading();
}
inline void SimplePlanning::clear_heading() {
  heading_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double SimplePlanning::_internal_heading() const {
  return heading_;
}
inline double SimplePlanning::heading() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimplePlanning.heading)
  return _internal_heading();
}
inline void SimplePlanning::_internal_set_heading(double value) {
  _has_bits_[0] |= 0x00000010u;
  heading_ = value;
}
inline void SimplePlanning::set_heading(double value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimplePlanning.heading)
}

// optional double speed = 6;
inline bool SimplePlanning::_internal_has_speed() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool SimplePlanning::has_speed() const {
  return _internal_has_speed();
}
inline void SimplePlanning::clear_speed() {
  speed_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double SimplePlanning::_internal_speed() const {
  return speed_;
}
inline double SimplePlanning::speed() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimplePlanning.speed)
  return _internal_speed();
}
inline void SimplePlanning::_internal_set_speed(double value) {
  _has_bits_[0] |= 0x00000020u;
  speed_ = value;
}
inline void SimplePlanning::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimplePlanning.speed)
}

// -------------------------------------------------------------------

// SimpleLocalization

// optional uint64 timestamp = 1;
inline bool SimpleLocalization::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SimpleLocalization::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void SimpleLocalization::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimpleLocalization::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimpleLocalization::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimpleLocalization.timestamp)
  return _internal_timestamp();
}
inline void SimpleLocalization::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  timestamp_ = value;
}
inline void SimpleLocalization::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimpleLocalization.timestamp)
}

// optional uint64 seq = 2;
inline bool SimpleLocalization::_internal_has_seq() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SimpleLocalization::has_seq() const {
  return _internal_has_seq();
}
inline void SimpleLocalization::clear_seq() {
  seq_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimpleLocalization::_internal_seq() const {
  return seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SimpleLocalization::seq() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimpleLocalization.seq)
  return _internal_seq();
}
inline void SimpleLocalization::_internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  seq_ = value;
}
inline void SimpleLocalization::set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimpleLocalization.seq)
}

// optional double x = 3;
inline bool SimpleLocalization::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SimpleLocalization::has_x() const {
  return _internal_has_x();
}
inline void SimpleLocalization::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double SimpleLocalization::_internal_x() const {
  return x_;
}
inline double SimpleLocalization::x() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimpleLocalization.x)
  return _internal_x();
}
inline void SimpleLocalization::_internal_set_x(double value) {
  _has_bits_[0] |= 0x00000004u;
  x_ = value;
}
inline void SimpleLocalization::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimpleLocalization.x)
}

// optional double y = 4;
inline bool SimpleLocalization::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool SimpleLocalization::has_y() const {
  return _internal_has_y();
}
inline void SimpleLocalization::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double SimpleLocalization::_internal_y() const {
  return y_;
}
inline double SimpleLocalization::y() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimpleLocalization.y)
  return _internal_y();
}
inline void SimpleLocalization::_internal_set_y(double value) {
  _has_bits_[0] |= 0x00000008u;
  y_ = value;
}
inline void SimpleLocalization::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimpleLocalization.y)
}

// optional double z = 5;
inline bool SimpleLocalization::_internal_has_z() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool SimpleLocalization::has_z() const {
  return _internal_has_z();
}
inline void SimpleLocalization::clear_z() {
  z_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double SimpleLocalization::_internal_z() const {
  return z_;
}
inline double SimpleLocalization::z() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimpleLocalization.z)
  return _internal_z();
}
inline void SimpleLocalization::_internal_set_z(double value) {
  _has_bits_[0] |= 0x00000010u;
  z_ = value;
}
inline void SimpleLocalization::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimpleLocalization.z)
}

// optional double heading = 6;
inline bool SimpleLocalization::_internal_has_heading() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool SimpleLocalization::has_heading() const {
  return _internal_has_heading();
}
inline void SimpleLocalization::clear_heading() {
  heading_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double SimpleLocalization::_internal_heading() const {
  return heading_;
}
inline double SimpleLocalization::heading() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SimpleLocalization.heading)
  return _internal_heading();
}
inline void SimpleLocalization::_internal_set_heading(double value) {
  _has_bits_[0] |= 0x00000020u;
  heading_ = value;
}
inline void SimpleLocalization::set_heading(double value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SimpleLocalization.heading)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace examples
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_class02_2eproto
